version: "3.9"

services:
  db:
    image: postgres:14
    container_name: telegram_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: telegram_app
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  pgdata: